import { SquarePen, Hash, Image, Eraser, FileText, House } from 'lucide-react';
import banner from '../assets/banner.jpg';
import placeholder from '../assets/placeholder.jpg';
import github from '../assets/github.svg';
import google from '../assets/google.svg';
import logo from '../assets/logo.svg';

export const countries = [
  { title: 'China', id: '+86' },
  { title: 'India', id: '+91' },
  { title: 'United States', id: '+1' },
  { title: 'Indonesia', id: '+62' },
  { title: 'Pakistan', id: '+92' },
  { title: 'Nigeria', id: '+234' },
  { title: 'Brazil', id: '+55' },
  { title: 'Bangladesh', id: '+880' },
  { title: 'Russia', id: '+7' },
  { title: 'Mexico', id: '+52' },
];

export const categories = [
  'beauty Nykaa',
  'fragrances',
  'furniture',
  'groceries',
  'home-decoration',
  'kitchen-accessories',
  'laptops',
  'mens-shirts',
  'mens-shoes',
  'mens-watches',
  'mobile-accessories',
  'motorcycle',
  'skin-care',
  'smartphones',
  'sports-accessories',
  'sunglasses',
  'tablets',
  'vehicle',
  'womens-bags',
  'womens-dresses',
  'womens-jewellery',
  'womens-shoes',
  'womens-watches',
];

export const brands = [
  'Amazon',
  'Annibale Colombo',
  'Apple',
  'Asus',
  'Attitude',
  'Bath Trends',
  'Beats',
  'Calvin Klein',
  'Casual Comfort',
  'Chanel',
  'Chic Cosmetics',
  'Chrysler',
  'Classic Wear',
  'Comfort Trends',
  'Dell',
  'Dior',
  'Dodge',
  'Dolce & Gabbana',
  'Elegance Collection',
  'Essence',
  'Fashion Co.',
  'Fashion Diva',
  'Fashion Express',
  'Fashion Fun',
  'Fashion Gold',
  'Fashion Shades',
  'Fashion Timepieces',
  'Fashion Trends',
  'Fashionista',
  'Furniture Co.',
  'GadgetMaster',
  'Generic Motors',
  'Gigabyte',
  'Glamour Beauty',
  'Gucci',
  'Heshe',
  'Huawei',
  'IWC',
  'Kawasaki',
  'Knoll',
  'Lenovo',
  'Longines',
  'MotoGP',
  'Nail Couture',
  'Nike',
  'Off White',
  'Olay',
  'Oppo',
  'Pampi',
  'Prada',
  'ProVision',
  'Puma',
  'Realme',
  'Rolex',
  'Samsung',
  'ScootMaster',
  'SnapTech',
  'SpeedMaster',
  'TechGear',
  'TempGear',
  'Urban Chic',
  'Vaseline',
  'Velvet Touch',
  'Vivo',
];

export const images = {
  banner,
  placeholder,
  github,
  google,
  logo,
};

export const aiToolsMenu = [
  {
    title: 'AI Tools',
    description:
      'Generate high-quality, engaging articles on any topic with our AI writing technology.',
    Icon: House,
    bg: { from: '#3588F2', to: '#0BB0D7' },
    path: '/tools',
  },
  {
    title: 'Article Writer',
    description:
      'Generate high-quality, engaging articles on any topic with our AI writing technology.',
    Icon: SquarePen,
    bg: { from: '#3588F2', to: '#0BB0D7' },
    path: '/tools/article-writer',
  },
  {
    title: 'Title Generator',
    description:
      'Find the perfect, catchy title for your blog posts with our AI-powered generator.',
    Icon: Hash,
    bg: { from: '#B153EA', to: '#E549A3' },
    path: '/tools/title-generator',
  },
  {
    title: 'Image Generator',
    description:
      'Create stunning visuals with our AI image generation tool, Experience the power of AI ',
    Icon: Image,
    bg: { from: '#20C363', to: '#11B97E' },
    path: '/tools/image-generator',
  },
  {
    title: 'Image Editor',
    description: 'Effortlessly remove backgrounds from your images with our AI-driven tool.',
    Icon: Eraser,
    bg: { from: '#f76c1c', to: '#ed4961' },
    path: '/tools/image-editor',
  },
  {
    title: 'Resume Reviewer',
    description:
      'Get your resume reviewed by AI to improve your chances of landing your dream job.',
    Icon: FileText,
    bg: { from: '#12B7AC', to: '#08B6CE' },
    path: '/tools/resume-reviewer',
  },
];
